### ISSUE TITLE
OpenCV Contrib for UWP: cannot find cmake despite the fact it exists

### ISSUE THREAD

**Issue by benjamincoven** [Microsoft/MixedRealityToolkit#199] opened 2019-01-11 13:50 UTC
Hello,

I am trying to install OpenCV Contrib for UWP but when runnin g the command line 
`.\vcpkg install opencv[contrib]:x86-uwp --recurse`

I am getting the following error:
`Extracting cmake... done.
Expected ***\vcpkg\downloads\tools\cmake-3.11.4-windows\cmake-3.11.4-win32-x86\bin\cmake.exe to exist after fetching`

However if I look at this folder path cmake.exe is present.

If I run the command a second time I get the same error as the issue #195 , deleting the downloads folder content get back to the previous situation.

Thank you.

**Comment by chrisfromwork** [comment] 2019-01-30 17:00
Hello,

What commit is your branch at for the vcpkg repo? This morning I was able sync with master (05b31030cee412118a9710daf5b4652a684b7f50). After running .\bootstrap-vcpkg.bat and your above install command, things seem to have succeeded with my local setup.

**Comment by chrisfromwork** [comment] 2019-01-30 17:44
I have gone ahead and committed a new readme that calls out using the newer commit. It looks like the newer version of vcpkg uses opencv 3.4.3 compared to 3.4.1. I've got a review out here showing how to update the plugin to the new open cv version: https://github.com/Microsoft/MixedRealityToolkit/pull/204

However, I am going to confirm that there are no logic regressions in opencv/spectatorview before checking in this opencv version change.

**Comment by benjamincoven** [comment] 2019-01-31 09:51
Thank you for your support.

Unfortunetly I got a new error when running the command `.\vcpkg install opencv[contrib]:x86-uwp --recurse` :

`CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: D:/UnityProjects/ArcelorIOSSV/vcpkg/buildtrees/tiff/x86-uwp-rel/vcpkg-parallel-configure
    See logs for more information:
      D:\UnityProjects\ArcelorIOSSV\vcpkg\buildtrees\tiff\config-x86-uwp-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:256 (vcpkg_execute_required_process)
  ports/tiff/portfile.cmake:25 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package tiff:x86-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: tiff:x86-uwp
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.`

Running this does nothing:
`.\vcpkg.exe update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.`

I am on commit 05b3103.

**Comment by benjamincoven** [comment] 2019-01-31 10:45
Retried all procedure on a fresh directory and it works fine.

**Closed** 2019-01-31 10:46 UTC
Labels: Documentation, SpectatorViewPlugin, bug
