### ISSUE TITLE
Serious mistake MixedRealityToolkit

### ISSUE THREAD

**Issue by HBJKZLH** [Microsoft/MixedRealityToolkit#148] opened 2018-02-28 10:56 UTC

**Comment by HBJKZLH** [comment] 2018-02-28 11:06
When I wrote socket and IO and Thread related code in the program, untiy packaging times was wrong,
The socket.Connect function is not supported.
The socket.Receive function is not supported, and the socket.Send function is not supported.
The filestream.close function is not supported,
New Thread(recv) is not supported,
Does not support Thread. IsBackground,
Does not support Thread. To Start,
What else can I develop?
Do you want me to develop model viewers only?

**Comment by davidkline-ms** [comment] 2018-05-10 19:55
closing as a duplicate of #149, which has more data than this issue

**Closed by davidkline-ms** 2018-05-10 19:55 UTC
